name: Build

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Try build on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          choco install ninja -y
          mkdir build
          mkdir build\мавка
          mkdir build\мавка\бібліотека
          mkdir build\МаМа
          mkdir build\МаМа\КД
          clang -c -o build\мавка\бібліотека\М.o .плавлення\мавка\бібліотека\М.ll 
          clang -c -o build\мавка\бібліотека\мавка.o .плавлення\мавка\бібліотека\мавка.ll 
          clang -c -o build\мавка\бібліотека\МаМа.o .плавлення\мавка\бібліотека\МаМа.ll 
          clang -c -o build\мавка\бібліотека\читати_юнікод.o .плавлення\мавка\бібліотека\читати_юнікод.ll 
          clang -c -o build\мавка\компілятор.o .плавлення\мавка\компілятор.ll 
          clang -c -o build\мавка\мавка.o .плавлення\мавка\мавка.ll 
          clang -c -o build\старт.o .плавлення\старт.ll 
          clang -c -o build\МаМа\КД\КД.o .плавлення\МаМа\КД\КД.ll 
          clang -c -o build\МаМа\біб.o .плавлення\МаМа\біб.ll 
          clang -c -o build\МаМа\Код.o .плавлення\МаМа\Код.ll 
          clang -c -o build\МаМа\Машина.o .плавлення\МаМа\Машина.ll 
          clang -c -o build\МаМа\Назва.o .плавлення\МаМа\Назва.ll 
          clang -c -o build\МаМа\Обʼєкт.o .плавлення\МаМа\Обʼєкт.ll 
          clang -c -o build\МаМа\ОбʼєктБайтів.o .плавлення\МаМа\ОбʼєктБайтів.ll 
          clang -c -o build\МаМа\ОбʼєктДії.o .плавлення\МаМа\ОбʼєктДії.ll 
          clang -c -o build\МаМа\ОбʼєктЛогічного.o .плавлення\МаМа\ОбʼєктЛогічного.ll 
          clang -c -o build\МаМа\ОбʼєктМодуля.o .плавлення\МаМа\ОбʼєктМодуля.ll 
          clang -c -o build\МаМа\ОбʼєктНативноїДії.o .плавлення\МаМа\ОбʼєктНативноїДії.ll 
          clang -c -o build\МаМа\ОбʼєктСловника.o .плавлення\МаМа\ОбʼєктСловника.ll 
          clang -c -o build\МаМа\ОбʼєктСписку.o .плавлення\МаМа\ОбʼєктСписку.ll 
          clang -c -o build\МаМа\ОбʼєктСтруктури.o .плавлення\МаМа\ОбʼєктСтруктури.ll 
          clang -c -o build\МаМа\ОбʼєктТексту.o .плавлення\МаМа\ОбʼєктТексту.ll 
          clang -c -o build\МаМа\ОбʼєктЮнікоду.o .плавлення\МаМа\ОбʼєктЮнікоду.ll 
          clang -c -o build\МаМа\ОбʼєктЧисла.o .плавлення\МаМа\ОбʼєктЧисла.ll 
          clang -c -o build\МаМа\Помилка.o .плавлення\МаМа\Помилка.ll 
          clang -c -o build\МаМа\Середовище.o .плавлення\МаМа\Середовище.ll 
          clang -c -o build\МаМа\СкладенийОбʼєкт.o .плавлення\МаМа\СкладенийОбʼєкт.ll 
          clang -c -o build\МаМа\Утилізатор.o .плавлення\МаМа\Утилізатор.ll 
          cd build
          cmake -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/LLVM/bin/clang.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files/LLVM/bin/clang.exe" -DCMAKE_LINKER:FILEPATH="C:/Program Files/LLVM/bin/lld-link.exe" -G "Ninja" ..\external -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always -DREADLINE_AVAILABLE=0
          ninja
          cd -
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mavka.exe
          path: build/mavka.exe
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v2
      #  if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/mavka.exe

