name: Build

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Try build on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -S. -Bbuild -G "Visual Studio 17 2022" -T ClangCL -A x64 ..\external -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always -DREADLINE_AVAILABLE=0
          make al
          cd -
          clang++ -municode -o build\mavka.exe .плавлення\мавка\бібліотека\М.ll .плавлення\мавка\бібліотека\мавка.ll .плавлення\мавка\бібліотека\МаМа.ll .плавлення\мавка\бібліотека\читати_юнікод.ll .плавлення\мавка\компілятор.ll .плавлення\мавка\мавка.ll .плавлення\старт.ll .плавлення\МаМа\КД\КД.ll .плавлення\МаМа\біб.ll .плавлення\МаМа\Код.ll .плавлення\МаМа\Машина.ll .плавлення\МаМа\Назва.ll .плавлення\МаМа\Обʼєкт.ll .плавлення\МаМа\ОбʼєктБайтів.ll .плавлення\МаМа\ОбʼєктДії.ll .плавлення\МаМа\ОбʼєктЛогічного.ll .плавлення\МаМа\ОбʼєктМодуля.ll .плавлення\МаМа\ОбʼєктНативноїДії.ll .плавлення\МаМа\ОбʼєктСловника.ll .плавлення\МаМа\ОбʼєктСписку.ll .плавлення\МаМа\ОбʼєктСтруктури.ll .плавлення\МаМа\ОбʼєктТексту.ll .плавлення\МаМа\ОбʼєктЮнікоду.ll .плавлення\МаМа\ОбʼєктЧисла.ll .плавлення\МаМа\Помилка.ll .плавлення\МаМа\Середовище.ll .плавлення\МаМа\СкладенийОбʼєкт.ll .плавлення\МаМа\Утилізатор.ll build\external\libmavka_external.a build\external\mavka_parser\libmavka_parser.a build\external\mavka_parser\syntax\libmavka_syntax.a build\external\mavka_parser\syntax\antlr4-cpp-runtime\libantlr4_cpp_runtime.a
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mavka.exe
          path: build/mavka.exe
          if-no-files-found: error
