# name: Build

# on:
#  push:
#    tags:
#      - "*.*.*-*"

# jobs:
#   deploy:
#     name: Try build for windows
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Build
#         run: |
#           export MAVKA_VERSION="$(cat ВЕРСІЯ)"
#           sudo snap install zig --classic --beta
#           sh build.sh
#           mkdir mavka-"$MAVKA_VERSION"
#           cp out/mavka.exe mavka-"$MAVKA_VERSION"
#           zip -r -9 mavka.zip mavka-"$MAVKA_VERSION"
#       - name: Release
#         uses: softprops/action-gh-release@v2
#         with:
#           files: mavka.zip
