name: Build

on:
 push:
   tags:
     - "*.*.*-*"

jobs:
  deploy:
    name: Try build for windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          export MAVKA_VERSION="$(cat ВЕРСІЯ)"
          sudo apt install -y ninja-build
          sudo snap install zig --classic --beta
          PLATFORM="w"
          export CC="zig cc -target x86_64-windows"
          export CXX="zig c++ -target x86_64-windows"
          export AR="zig ar"
          export RANLIB="zig ranlib"
          export USE_JEMALLOC=no
          export USE_SYSTEMD=no
          export TSIL="ціль"
          OUT="build-$PLATFORM/mavka.exe"
          mkdir -p build-w
          CXX_OPTIONS=(
            "-O3"
            "-municode"
          )
          $CXX "${CXX_OPTIONS[@]}" -o "$OUT" \
            .плавлення/мавка/бібліотека/М.ll \
            .плавлення/мавка/бібліотека/мавка.ll \
            .плавлення/мавка/бібліотека/МаМа.ll \
            .плавлення/мавка/бібліотека/читати_юнікод.ll \
            .плавлення/мавка/розбирач/розбирач.ll \
            .плавлення/мавка/компілятор/компілятор.ll \
            .плавлення/мавка/математика.ll \
            .плавлення/мавка/система.ll \
            .плавлення/мавка/допоміжне.ll \
            .плавлення/мавка/мавка.ll \
            .плавлення/старт.ll \
            .плавлення/МаМа/КД/КД.ll \
            .плавлення/МаМа/біб.ll \
            .плавлення/МаМа/Код.ll \
            .плавлення/МаМа/Машина.ll \
            .плавлення/МаМа/Назва.ll \
            .плавлення/МаМа/Предмет.ll \
            .плавлення/МаМа/ПредметАдреси.ll \
            .плавлення/МаМа/ПредметБайтів.ll \
            .плавлення/МаМа/ПредметДії.ll \
            .плавлення/МаМа/ПредметЛогічного.ll \
            .плавлення/МаМа/ПредметМодуля.ll \
            .плавлення/МаМа/ПредметНативноїДії.ll \
            .плавлення/МаМа/ПредметСловника.ll \
            .плавлення/МаМа/ПредметСписку.ll \
            .плавлення/МаМа/ПредметСтруктури.ll \
            .плавлення/МаМа/ПредметТексту.ll \
            .плавлення/МаМа/ПредметЮнікоду.ll \
            .плавлення/МаМа/ПредметЧисла.ll \
            .плавлення/МаМа/Помилка.ll \
            .плавлення/МаМа/Середовище.ll \
            .плавлення/МаМа/СкладенийПредмет.ll \
            .плавлення/МаМа/Утилізатор.ll \
            external/mavka.cpp
          mkdir mavka-"$MAVKA_VERSION"
          cp build-"$PLATFORM"/mavka.exe mavka-"$MAVKA_VERSION"
          zip -r -9 mavka.zip mavka-"$MAVKA_VERSION"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mavka.zip
